# Generated by Django 4.1.7 on 2023-03-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_rename_user_organization_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAnalyzedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Группа элементов')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название анализируемого элемента')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.groupanalyzeditems')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_item', to='monitoring.analyzeditem')),
            ],
        ),
    ]
