# Generated by Django 4.1.7 on 2023-03-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_rename_analyseditemssummarystatistics_analyzeditemssummarystatistics_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analyzeditemkeywords',
            table='analyzed_item_keywords',
        ),
    ]
