# Generated by Django 4.1.7 on 2023-04-20 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0030_alter_groupanalyzeditems_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
