# Generated by Django 4.1.7 on 2023-04-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_remove_organization_users_organization_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
    ]
