# Generated by Django 4.1.7 on 2023-05-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_app', '0010_alter_vksettings_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkignoreusers',
            old_name='organization',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='vksettings',
            old_name='organization',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='vkuser',
            old_name='organization',
            new_name='team',
        ),
    ]
