# Generated by Django 4.1.7 on 2023-05-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_app', '0013_rename_search_item_vkpost_analysed_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkpost',
            old_name='analysed_item',
            new_name='search_item',
        ),
    ]
