# Generated by Django 4.1.7 on 2023-03-21 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0014_alter_analyzeditem_date_create_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VkUserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_api_app.vkuserstatistic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Токен авторизации vk')),
                ('group_id', models.IntegerField(verbose_name='Id группы в vk')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField(verbose_name='ID поста')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('likes', models.IntegerField(verbose_name='Количество лайков')),
                ('comments', models.IntegerField(verbose_name='Количество комментариев')),
                ('reposts', models.IntegerField(verbose_name='Количество "Поделиться"')),
                ('views', models.IntegerField(verbose_name='Количество просмотров')),
                ('analysed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.analyzeditem')),
            ],
        ),
    ]
