# Generated by Django 4.1.7 on 2023-03-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_alter_groupanalyzeditems_organization'),
        ('vk_api_app', '0002_remove_vkuser_user_vkuser_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.organization'),
        ),
    ]
