# Generated by Django 4.1.7 on 2023-04-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_alter_groupanalyzeditems_level'),
        ('vk_api_app', '0004_alter_vkuser_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkIgnoreUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.organization')),
            ],
        ),
    ]
