# Generated by Django 4.1.7 on 2023-04-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_app', '0006_vkusersummarystatistics_remove_vkuser_statistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuserstatistic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_api_app.vkuser'),
        ),
    ]
