# Generated by Django 4.1.7 on 2023-03-14 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
            ],
        ),
    ]
