# Generated by Django 4.1.7 on 2023-03-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_groupanalyzeditems_analyzeditem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupanalyzeditems',
            table='monitoring_group_analyzed_items',
        ),
    ]
