# Generated by Django 4.1.7 on 2023-03-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_groupanalyzeditems_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analyzeditem',
            table='monitoring_analyzed_item',
        ),
    ]
