# Generated by Django 4.1.7 on 2023-03-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_analyseditemssummarystatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.TextField(default=0)),
                ('comment', models.TextField(default=0)),
                ('reports', models.TextField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.analyzeditem')),
            ],
            options={
                'db_table': 'monitoring_statistics',
            },
        ),
    ]
