# Generated by Django 4.1.7 on 2023-03-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_statistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyseditemssummarystatistics',
            old_name='comment',
            new_name='comments',
        ),
    ]
