# Generated by Django 4.1.7 on 2023-03-17 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_rename_comment_analyseditemssummarystatistics_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzeditem',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.organization'),
        ),
        migrations.AlterField(
            model_name='analyzeditem',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 11, 32, 36, 900579, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='analyzeditem',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 11, 32, 36, 900604, tzinfo=datetime.timezone.utc)),
        ),
    ]
