# Generated by Django 4.1.7 on 2023-03-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_groupanalyzeditems_ru_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupanalyzeditems',
            name='ru_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Русское имя группы элементов'),
        ),
    ]
