# Generated by Django 4.1.7 on 2023-03-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_alter_groupanalyzeditems_ru_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupanalyzeditems',
            name='user',
        ),
        migrations.AddField(
            model_name='groupanalyzeditems',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.organization'),
        ),
    ]
