# Generated by Django 4.1.7 on 2023-03-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_rename_comment_statistics_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyseditemssummarystatistics',
            old_name='reports',
            new_name='reposts',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='reports',
            new_name='reposts',
        ),
    ]
