# Generated by Django 4.1.7 on 2023-03-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_alter_analyzeditemkeywords_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analyzeditemkeywords',
            table='monitoring_analyzed_item_keywords',
        ),
    ]
