# Generated by Django 4.1.7 on 2023-04-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_alter_analyzeditemkeywords_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzeditemssummarystatistics',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary_statistics', serialize=False, to='monitoring.analyzeditem'),
        ),
    ]
