# Generated by Django 4.1.7 on 2023-04-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_alter_analyzeditemssummarystatistics_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupanalyzeditems',
            name='level',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
