# Generated by Django 4.1.7 on 2023-05-09 22:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vk_api_app', '0011_rename_organization_vkignoreusers_team_and_more'),
        ('monitoring', '0037_alter_organization_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='analyzeditem',
            old_name='organization',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='groupanalyzeditems',
            old_name='organization',
            new_name='team',
        ),
    ]
