# Generated by Django 4.1.7 on 2023-05-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_app', '0011_rename_organization_vkignoreusers_team_and_more'),
        ('monitoring', '0038_rename_organization_team_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupAnalyzedItems',
            new_name='GroupSearchItems',
        ),
        migrations.RenameModel(
            old_name='AnalyzedItem',
            new_name='SearchItem',
        ),
        migrations.RenameModel(
            old_name='AnalyzedItemKeyWords',
            new_name='SearchItemKeywords',
        ),
        migrations.RenameModel(
            old_name='AnalyzedItemsSummaryStatistics',
            new_name='SearchItemsSummaryStatistics',
        ),
    ]
