# Generated by Django 4.1.7 on 2023-05-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0041_rename_groupanalyzeditems_groupsearchitems_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupsearchitems',
            table='monitoring_group_search_items',
        ),
        migrations.AlterModelTable(
            name='searchitem',
            table='monitoring_search_item',
        ),
        migrations.AlterModelTable(
            name='searchitemkeywords',
            table='monitoring_search_item_keywords',
        ),
        migrations.AlterModelTable(
            name='searchitemssummarystatistics',
            table='monitoring_search_items_summary_statistics',
        ),
    ]
