# Generated by Django 4.1.7 on 2023-05-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0042_alter_groupsearchitems_table_alter_searchitem_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_item', to='monitoring.searchitem'),
        ),
    ]
