# Generated by Django 4.1.7 on 2023-09-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0043_alter_searchitem_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchitem',
            old_name='date_create',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='searchitem',
            old_name='last_update',
            new_name='time_update',
        ),
    ]
