# Generated by Django 4.1.7 on 2023-05-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitation',
            table='user_invitation',
        ),
    ]
